"""Dependency-free assurance domain vocabulary."""

from assurance.domain.enums import (
    ApprovalOutcome,
    AssuranceStatus,
    AuthorityRole,
    CanonicalAction,
    Classification,
    ConditionStatus,
    DomainVerb,
    EconomicMetric,
    EvidenceKind,
    EvidenceVerificationOutcome,
    ExecutionGateResult,
    ExecutionOutcome,
    ExplanationCode,
    FieldPath,
    LifecycleState,
    NonPermissiveEffect,
    PolicyParameterKey,
    PredicateOperator,
    PrincipalType,
    QueryType,
    ReceiptKind,
    RequirementStatus,
    ResourceType,
    RouteId,
    StreamType,
    SubjectRole,
    Verdict,
)

__all__ = [
    "ApprovalOutcome",
    "AssuranceStatus",
    "AuthorityRole",
    "CanonicalAction",
    "Classification",
    "ConditionStatus",
    "DomainVerb",
    "EconomicMetric",
    "EvidenceKind",
    "EvidenceVerificationOutcome",
    "ExecutionGateResult",
    "ExecutionOutcome",
    "ExplanationCode",
    "FieldPath",
    "LifecycleState",
    "NonPermissiveEffect",
    "PolicyParameterKey",
    "PredicateOperator",
    "PrincipalType",
    "QueryType",
    "ReceiptKind",
    "RequirementStatus",
    "ResourceType",
    "RouteId",
    "StreamType",
    "SubjectRole",
    "Verdict",
]

