"""Finite domain vocabularies.

These enums describe contract values only. They contain no routing or policy
evaluation behavior.
"""

from enum import StrEnum


class Classification(StrEnum):
    SOURCED = "SOURCED"
    OBSERVED = "OBSERVED"
    ESTIMATED = "ESTIMATED"
    INFERRED = "INFERRED"
    UNRESOLVED = "UNRESOLVED"
    FINANCIALLY_RECONCILED = "FINANCIALLY_RECONCILED"


class PrincipalType(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    SERVICE = "SERVICE"
    APPLICATION = "APPLICATION"


class CanonicalAction(StrEnum):
    OBSERVE = "OBSERVE"
    INFER = "INFER"
    COMMUNICATE = "COMMUNICATE"
    MODIFY = "MODIFY"
    COMMIT = "COMMIT"
    TRANSFER = "TRANSFER"
    DELEGATE = "DELEGATE"


class DomainVerb(StrEnum):
    DISCLOSE = "DISCLOSE"
    ADVANCE_SUPPLIER = "ADVANCE_SUPPLIER"
    APPROVE = "APPROVE"
    ACTIVATE_SUPPLIER = "ACTIVATE_SUPPLIER"


class ResourceType(StrEnum):
    SUPPLIER = "SUPPLIER"


class RouteId(StrEnum):
    AUTONOMOUS_SUPPLIER = "AUTONOMOUS_SUPPLIER"
    HUMAN_SUPPLIER_REVIEW = "HUMAN_SUPPLIER_REVIEW"


class LifecycleState(StrEnum):
    DRAFT = "DRAFT"
    REVIEWED = "REVIEWED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class Verdict(StrEnum):
    ALLOW = "ALLOW"
    ALLOW_WITH_CONDITIONS = "ALLOW_WITH_CONDITIONS"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    SWITCH_ROUTE = "SWITCH_ROUTE"
    BLOCK = "BLOCK"
    CONFLICT = "CONFLICT"


class PredicateOperator(StrEnum):
    EQ = "EQ"
    IN = "IN"
    LT = "LT"
    LTE = "LTE"
    GT = "GT"
    GTE = "GTE"
    EXISTS = "EXISTS"


class NonPermissiveEffect(StrEnum):
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    SWITCH_ROUTE = "SWITCH_ROUTE"
    BLOCK = "BLOCK"


class FieldPath(StrEnum):
    INTENT_CANONICAL_ACTION = "intent.canonical_action"
    INTENT_DOMAIN_VERB = "intent.domain_verb"
    INTENT_PRINCIPAL_TYPE = "intent.principal.principal_type"
    INTENT_RESOURCE_TYPE = "intent.resource.resource_type"
    INTENT_REQUESTED_STATE_CHANGE = "intent.requested_state_change"
    FACT_SUPPLIER_CRITICALITY = "fact.supplier.criticality"
    FACT_RELATIONSHIP_DATA_CLASSIFICATION = "fact.relationship.data_classification"
    FACT_DESTINATION_APPROVED = "fact.destination.approved"
    FACT_PRIVACY_REVIEW_VALID = "fact.privacy_review.valid"
    METER_AUTONOMOUS_ATTEMPTS = "meter.autonomous_attempts"
    METER_COST_TO_DATE_MINOR = "meter.cost_to_date_minor"


class AuthorityRole(StrEnum):
    RISK_OWNER = "RISK_OWNER"
    REVIEWER = "REVIEWER"
    POLICY_APPROVER = "POLICY_APPROVER"
    POLICY_PUBLISHER = "POLICY_PUBLISHER"
    OPERATOR = "OPERATOR"
    ADVANCEMENT_APPROVER = "ADVANCEMENT_APPROVER"
    EXCEPTION_AUTHORITY = "EXCEPTION_AUTHORITY"
    EVIDENCE_CERTIFIER = "EVIDENCE_CERTIFIER"
    INDEPENDENT_ASSESSOR = "INDEPENDENT_ASSESSOR"


class SubjectRole(StrEnum):
    ACTOR = "ACTOR"
    PROPOSER = "PROPOSER"
    EXECUTOR = "EXECUTOR"
    APPROVER = "APPROVER"
    EVIDENCE_PRODUCER = "EVIDENCE_PRODUCER"
    EVIDENCE_CERTIFIER = "EVIDENCE_CERTIFIER"
    INDEPENDENT_ASSESSOR = "INDEPENDENT_ASSESSOR"


class EvidenceKind(StrEnum):
    THIRD_PARTY_RISK_REVIEW = "THIRD_PARTY_RISK_REVIEW"
    DATA_DESTINATION_APPROVAL = "DATA_DESTINATION_APPROVAL"
    PRIVACY_REVIEW = "PRIVACY_REVIEW"
    EXECUTION_RESULT = "EXECUTION_RESULT"
    FINANCIAL_RECONCILIATION = "FINANCIAL_RECONCILIATION"


class EconomicMetric(StrEnum):
    ATTEMPT_COUNT = "ATTEMPT_COUNT"
    COST_MINOR_UNITS = "COST_MINOR_UNITS"


class RequirementStatus(StrEnum):
    SATISFIED = "SATISFIED"
    UNSATISFIED = "UNSATISFIED"
    UNKNOWN = "UNKNOWN"


class ConditionStatus(StrEnum):
    SATISFIED = "SATISFIED"
    OUTSTANDING = "OUTSTANDING"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class ApprovalOutcome(StrEnum):
    GRANTED = "GRANTED"
    DENIED = "DENIED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class EvidenceVerificationOutcome(StrEnum):
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ExecutionGateResult(StrEnum):
    AUTHORIZED = "AUTHORIZED"
    REJECTED = "REJECTED"


class ExecutionOutcome(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"
    NOT_EXECUTED = "NOT_EXECUTED"


class TargetKeyPurpose(StrEnum):
    TARGET_AUTHORIZATION = "TARGET_AUTHORIZATION"
    TARGET_RESULT = "TARGET_RESULT"


class TargetDispatchState(StrEnum):
    PENDING = "PENDING"
    LEASED = "LEASED"
    DELIVERED = "DELIVERED"
    OUTCOME_UNRESOLVED = "OUTCOME_UNRESOLVED"


class TargetDispatchEventKind(StrEnum):
    LEASED = "LEASED"
    DELIVERED = "DELIVERED"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    OUTCOME_UNRESOLVED = "OUTCOME_UNRESOLVED"


class AssuranceStatus(StrEnum):
    ASSURANCE_SUCCEEDED = "ASSURANCE_SUCCEEDED"
    ASSURANCE_INCOMPLETE = "ASSURANCE_INCOMPLETE"
    ASSURANCE_FAILED = "ASSURANCE_FAILED"


class ReceiptKind(StrEnum):
    INITIAL = "INITIAL"
    CORRECTION = "CORRECTION"
    REOPENING = "REOPENING"
    REVERSAL = "REVERSAL"


class QueryType(StrEnum):
    RESOLVED_FACTS = "RESOLVED_FACTS"
    EFFECTIVE_POLICY = "EFFECTIVE_POLICY"
    AUTHORITY_GRANTS = "AUTHORITY_GRANTS"
    LINEAGE_MEMBERSHIPS = "LINEAGE_MEMBERSHIPS"
    EVIDENCE_EVENTS = "EVIDENCE_EVENTS"
    ECONOMIC_METERS = "ECONOMIC_METERS"


class StreamType(StrEnum):
    SPEC_LIFECYCLE = "SPEC_LIFECYCLE"
    HUMAN_DECISION = "HUMAN_DECISION"
    AUTHORITY_GRANT = "AUTHORITY_GRANT"
    LINEAGE_MEMBERSHIP = "LINEAGE_MEMBERSHIP"
    EVIDENCE = "EVIDENCE"
    ECONOMIC_METER = "ECONOMIC_METER"
    RECEIPT = "RECEIPT"


class ExplanationCode(StrEnum):
    REQUIREMENTS_SATISFIED = "REQUIREMENTS_SATISFIED"
    CONDITIONS_OUTSTANDING = "CONDITIONS_OUTSTANDING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    ROUTE_SWITCH_REQUIRED = "ROUTE_SWITCH_REQUIRED"
    MATCHED_PROHIBITION = "MATCHED_PROHIBITION"
    INCOMPATIBLE_MANDATORY_ROUTES = "INCOMPATIBLE_MANDATORY_ROUTES"
    NO_SAFE_PUBLISHED_RULE = "NO_SAFE_PUBLISHED_RULE"
    MISSING_CONTEXT = "MISSING_CONTEXT"
    AMBIGUOUS_POLICY_SELECTION = "AMBIGUOUS_POLICY_SELECTION"
    AUTHORITY_MISSING = "AUTHORITY_MISSING"
    INDEPENDENCE_FAILED = "INDEPENDENCE_FAILED"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    ECONOMIC_CAP_EXCEEDED = "ECONOMIC_CAP_EXCEEDED"
    REAUTHORIZATION_REQUIRED = "REAUTHORIZATION_REQUIRED"


class PolicyParameterKey(StrEnum):
    EVIDENCE_VALIDITY_SECONDS = "EVIDENCE_VALIDITY_SECONDS"
    APPROVAL_VALIDITY_SECONDS = "APPROVAL_VALIDITY_SECONDS"
    AUTONOMOUS_ATTEMPT_LIMIT = "AUTONOMOUS_ATTEMPT_LIMIT"
    TOTAL_COST_LIMIT_MINOR = "TOTAL_COST_LIMIT_MINOR"
    ROUTINE_POSITIVE_VERDICT = "ROUTINE_POSITIVE_VERDICT"
    REQUIRED_EVIDENCE_KIND = "REQUIRED_EVIDENCE_KIND"
    REQUIRED_APPROVER_ROLE = "REQUIRED_APPROVER_ROLE"


class WorkflowEnvironment(StrEnum):
    LOCAL_TEST = "LOCAL_TEST"
    LOCAL_DEMO = "LOCAL_DEMO"


class WorkflowState(StrEnum):
    DRAFT = "DRAFT"
    CONFIGURED = "CONFIGURED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class DeploymentState(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    RETIRED = "RETIRED"


class EnforcementPointState(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class MappingState(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class ConnectorState(StrEnum):
    DRAFT = "DRAFT"
    CONFIGURED = "CONFIGURED"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    DISABLED = "DISABLED"
    RETIRED = "RETIRED"


class ConnectorKind(StrEnum):
    INBOUND = "INBOUND"
    TARGET = "TARGET"
    EVIDENCE = "EVIDENCE"
    REPORTING = "REPORTING"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class ConnectorOperation(StrEnum):
    RECEIVE_EVENT = "RECEIVE_EVENT"
    INVOKE_TARGET = "INVOKE_TARGET"
    FETCH_EVIDENCE = "FETCH_EVIDENCE"
    PUBLISH_REPORT = "PUBLISH_REPORT"
    CREATE_WORK_ITEM = "CREATE_WORK_ITEM"


class ConnectorHealth(StrEnum):
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    DISABLED = "DISABLED"


class EnforcementMode(StrEnum):
    TEST = "TEST"
    SHADOW = "SHADOW"
    ENFORCED = "ENFORCED"
    PAUSED = "PAUSED"
    RETIRED = "RETIRED"


class ShadowRunState(StrEnum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class ShadowDisposition(StrEnum):
    OBSERVED = "OBSERVED"
    REJECTED_WITH_REASON = "REJECTED_WITH_REASON"
    DUPLICATE_OF = "DUPLICATE_OF"
    CANCELLED = "CANCELLED"
    AUTHENTICATED_SOURCE_FAILURE = "AUTHENTICATED_SOURCE_FAILURE"
    UNEXPLAINED = "UNEXPLAINED"


class ShadowComparisonCode(StrEnum):
    INCOMPLETE_COMPARISON = "INCOMPLETE_COMPARISON"
    POLICY_CONFLICT = "POLICY_CONFLICT"
    ACTUAL_ROUTE_NOT_PERMITTED = "ACTUAL_ROUTE_NOT_PERMITTED"
    REQUIRED_APPROVAL_MISSING = "REQUIRED_APPROVAL_MISSING"
    REQUIRED_EVIDENCE_MISSING = "REQUIRED_EVIDENCE_MISSING"
    RISK_CONTEXT_MISSING = "RISK_CONTEXT_MISSING"
    RISK_SPEC_MORE_RESTRICTIVE = "RISK_SPEC_MORE_RESTRICTIVE"
    ACTUAL_WORKFLOW_MORE_RESTRICTIVE = "ACTUAL_WORKFLOW_MORE_RESTRICTIVE"
    MATCH = "MATCH"


class ReadinessCode(StrEnum):
    POLICY_REVALIDATION_REQUIRED = "POLICY_REVALIDATION_REQUIRED"
    WORKFLOW_NOT_ACTIVE = "WORKFLOW_NOT_ACTIVE"
    DEPLOYMENT_NOT_PUBLISHED = "DEPLOYMENT_NOT_PUBLISHED"
    ENFORCEMENT_POINT_NOT_ACTIVE = "ENFORCEMENT_POINT_NOT_ACTIVE"
    CONNECTOR_NOT_ACTIVE = "CONNECTOR_NOT_ACTIVE"
    CONNECTOR_HEALTH_STALE = "CONNECTOR_HEALTH_STALE"
    MAPPING_NOT_PUBLISHED = "MAPPING_NOT_PUBLISHED"
    PROTECTED_TARGET_INVENTORY_INCOMPLETE = "PROTECTED_TARGET_INVENTORY_INCOMPLETE"
    POLICY_COVERAGE_INCOMPLETE = "POLICY_COVERAGE_INCOMPLETE"
    POLICY_CONFLICT = "POLICY_CONFLICT"
    SHADOW_POPULATION_INCOMPLETE = "SHADOW_POPULATION_INCOMPLETE"
    SHADOW_BLOCKING_GAP = "SHADOW_BLOCKING_GAP"
    REPRESENTATIVE_TEST_FAILED = "REPRESENTATIVE_TEST_FAILED"
    REQUIRED_APPROVAL_MISSING = "REQUIRED_APPROVAL_MISSING"
    UNRESOLVED_HUMAN_DECISION = "UNRESOLVED_HUMAN_DECISION"
    STALE_EXPECTED_HEAD = "STALE_EXPECTED_HEAD"
    TAMPER_DETECTED = "TAMPER_DETECTED"


class EnforcementDisposition(StrEnum):
    PROCEED = "PROCEED"
    USE_APPROVED_FALLBACK = "USE_APPROVED_FALLBACK"
    STOP_NO_TARGET = "STOP_NO_TARGET"


class MappingPresence(StrEnum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"


class MappingSource(StrEnum):
    EVENT = "EVENT"
    TARGET_RESULT = "TARGET_RESULT"


class MappingConversion(StrEnum):
    UUID = "UUID"
    INTEGER = "INTEGER"
    BOOLEAN = "BOOLEAN"
    STRING = "STRING"
    TIMESTAMP = "TIMESTAMP"
    MONEY = "MONEY"


class MappingOutputPath(StrEnum):
    PRINCIPAL_EXTERNAL_SUBJECT = "principal.external_subject"
    BEHALF_OF_PARTY_ID = "behalf_of_party_id"
    DOMAIN_VERB = "domain_verb"
    CANONICAL_ACTION = "canonical_action"
    RESOURCE_BUSINESS_ID = "resource.business_id"
    RESOURCE_EXPECTED_VERSION = "resource.expected_version"
    REQUESTED_STATE_CHANGE = "requested_state_change"
    REQUESTED_ROUTE = "requested_route"
    EVIDENCE_REFS = "evidence_refs"
    REQUESTED_AT = "requested_at"
    SOURCE_SEQUENCE = "source_sequence"


class OutcomeOutputPath(StrEnum):
    TARGET_OUTCOME = "target_outcome"
    ACTUAL_ROUTE = "actual_route"
    EVIDENCE_REFS = "evidence_refs"
    TARGET_RESOURCE_VERSION = "target_resource_version"


class DeploymentApprovalKind(StrEnum):
    WORKFLOW_OWNER = "WORKFLOW_OWNER"
    RISK_CHALLENGE = "RISK_CHALLENGE"


class DeploymentApprovalOutcome(StrEnum):
    GRANTED = "GRANTED"
    DENIED = "DENIED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
